ansible/community

CONTRIBUTING.md
MEETINGLOGS.md
README.md

Creating space to capture meeting logs. Note: in the future, IRC logs could probably dump into a /meetings subdirectory that we can point to, though we would probably still keep this space around for documenting in-person events, and just link to the subdirectory to see things from #ansible-meeting.

Create MEETINGLOGS.md, closes ansible/community#19

---

MEETINGS.md

These duckduckgo answers will show the current time in the user's timezone.

Provide easy duckduckgo answers links to standard UTC times

---

MEETINGS.md

Only problem is that it's only 1 hour after the Core meeting.
cc: @nitzmahone

Added new Windows meeting schedule

---

group-aws/README.md
group-aws/bestpractices.md
group-aws/boto3.md
group-aws/integration.md
group-aws/refactor.md
group-aws/review.md

Lots of room for improvement, including
relating existing PRs to any of these pages.
If we can automate the generation of the lists
from AWS labels, so much the better.

First pass at AWS Working Group goals

---

meetings/ical/network.ics
meetings/network.yaml

Now that we have meeting bot (`@zobot`) in `#ansible-network` lets move the meetings there.

ansible-network for meetings

---

group-network/network_dev_network_cli.rst

To allow faster updates we are initially creating this document in the
Community site, once the content is mostly correct we will move the
content to Ansible:docs/docsite/rst/dev_guide

How to create network_cli modules

---

group-aws/boto3.md
group-aws/integration.md
group-aws/review.md

Add stats
Also add integration test policy for new modules following release of 2.5 (don't want to arbitrarily change policy today as that would affect modules currently progress).

Update AWS stats for December

---

group-network/roles_development_process.rst

- Added entry in doc on how to handle 404s while accessing ```{{ repo }}/settings/branches```

network-roles-dev-docs: Add entry to handle 404s

---

group-network/roles_development_process.rst

The ansible-network is now a dedicated zuul tenant with a new resource file location.
This change updates the reference and fixes the link to use ansible-network.sf-project.io

Update ansible-network zuul usage instruction

---

group-aws/boto3.md

Add some more boto -> boto3 migrations
rds_ modules are listed as they are replacing pieces of the rds module

[aws] add some more boto -> boto3 migrations

---

README.md

* We are using GitHub project boards, not waffle boards
* Remove old contributing info
* Combine groups & IRC channels sections plus add docs, linode, Galaxy
* List all IRC channels `/msg alis LIST #ansible*`

Tidy up IRC & Group list

---

group-linode/README.md

Follows https://github.com/ansible/ansible/pull/46642.
cc @rmcintosh.

Add rmcintosh to the wiki listing for Linode.

---

README.md

It is IRC channel  #ansibleu that has habitants.    ( #ansibleeu is empty )

ansibleu,  1 e

---

meetings/README.md

@aknrdureegaesr pointed out on IRC that the DaWG (Documentation Working Group) meetings were not listed on the `meetings/README` page.
This PR updates the `meetings/README` page to reflect the current slate of meetings, based on the files in https://github.com/ansible/community/tree/master/meetings/ical.

updates calendar/list on meetings/README

---

decks/contributing-to-ansible.html

Mostly changes to grammar, punctuation, and layout.
Removed references to "using the chat" from when we did this as a webinar.
Removed AnsibleFest link.

Update Fest slides for gundalow/acozine presentation

---

decks/intro-to-ansible-tower.html

There is no space in the official brand name, DigitalOcean. :)

typo: Digital Ocean --> DigitalOcean

---

meetings/read_minutes.py

For example most of the actions in https://meetbot-raw.fedoraproject.org/ansible-community/2020-07-22/ansible_community_meeting.2020-07-22-18.00.txt need two lines. The script only extracts the first line.
CC @samccann @gundalow

read_minutes: do not cut off multiline actions

---

ansible_community_meetings.ics

D&I meeting was added as a separate calendar rather than just a separate event in the main calendar. Fixes the copy-paste error.

Remove extra lines in iCalendar Object

---

ansible_community_meetings.ics
meetings/core-team.yaml
meetings/ical/core-team.ics

Now that we have transitioned to alternating meetings, update the schedule with the generated output rather than relying on custom changes to the ics files.

Update Ansible Core weekly meetings

---

README.md
WORKING-GROUPS.md
decks/contrib-summit-2021.03/3.0.0-community-update.html
decks/contributing-to-ansible.html
group-aws/README.md
group-network/network_dev_network_cli.rst
group-network/network_test.rst
group-security/README.md
meetings/README.md

ansible channels have moved to libera.chat.
Do not merge until it's decided that we're moving to libera.chat (as opposed to oftc or another network): https://github.com/ansible-community/community-topics/issues/19

Due to the takeover of freenode we're moving to a different irc network.

---

ansible_community_meetings.ics
meetings/docs.yaml

Push to 16:00 UTC so that the time remains at 11AM ET once daylight savings ends. See https://github.com/ansible/community/issues/579#issuecomment-946884014.
Also need to edit https://github.com/ansible/community/wiki/Docs to say 16:00 UTC.
And change matrix reminder bot to move the DING DING DING reminder out to 15:00 UTC (on hour before the meeting), and the room cyb-clock-clone meeting reminders every 15 minutes during the meeting.

update DaWGs meeting to one hour later UTC for Winter

---

meetings/ical/contribsummit202204.ics

Ansible Contributor Summit 2022.04 will be held on April 12, 2022 (Tuesday). The ical file will make it easier for people to add the event to their calendars.

Add ical file for Contributor Summit 2022.04

---

ansible_community_meetings.ics
meetings/core-team.yaml
meetings/ical/core-team.ics

This change moves the Core IRC meetings to happen once a month at 1600 UTC on the 2nd Thursday of the month.
If topics are more urgent, they can be brought up in advance in #ansible-devel

Migrate Core IRC meetings to 1 time per month

---

ansible_community_meetings.ics
meetings/README.md
meetings/docs.yaml
meetings/ical/docs.ics

Keeping the DaWGs meeting at its normal time (11am ET) after the time change.
Also need to change remindbot in matrix...
hange matrix reminder bot to move the DING DING DING reminder to 15:00 UTC (one hour before the meeting)
(something like !remindroom cron 0 15 * * 2 ; "DING DING DING! DaWGs (documentation working group meeting) happening in 1 hour") to happen at 1500 hrs on a Tuesday
(see https://github.com/anoadragon453/matrix-reminder-bot)

update DaWGs meeting for end of DST

---

ansible_community_meetings.ics
meetings/community.yaml
meetings/ical/community.ics

Summer time begins for (most of) the Europe on 26 March. It started in the US back on 12 March. After last time change, we informally agreed to move the meeting according to winter and summer time (i.e. meet at 19:00 in the winter and 18:00 in the summer).

switch community meeting to 18:00 UTC

---

ansible_community_meetings.ics
meetings/README.md
meetings/docs.yaml
meetings/ical/docs.ics

Time to shift the meeting again to 15:00 UTC to account for daylight savings changes. This brings the meeting back to it's 'usual' time for places that have already shifted to daylight savings time

Shift DaWGs meeting to DST

---

ansible_community_meetings.ics
meetings/README.md
meetings/ical/network.ics
meetings/ical/windows.ics
meetings/network.yaml
meetings/windows.yaml

This also fixes the Windows meeting definition so that the calendars generate properly, and fixes the remainder of #656 since I had to edit that list anyway.

Shift networking meeting time

---

ansible_community_meetings.ics

The Core Team meeting was removed from everywhere except the combined
ansible_community_meetings.ics file in
ced488324e6aa4704c5f070dafabb8176496ea0e.

fully remove Core Team meeting

---

ansible_community_meetings.ics
meetings/README.md
meetings/docs.yaml
meetings/ical/docs.ics

Also updated the agenda link to point to the forum now.
Steps to implement:
update docs.yaml
~/community/meetings (dawgs-dst) $ make all
`git checkout HEAD` to  revert the other files and other entries in ansible_community_meetings.ics

update Docs meeting for end of daylight savings time

---

README.md

As part of the effort to [Archive this repository](https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928/1), adding a note in the readme on where to find presentations going forward.

Add breadcrumb to where presentations now live
