MEETINGS.md

Add details explaining the purpose of the Core meeting, based on @abadger's description
Improve layout and formatting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/community/76)

Flesh out purpose and agenda

---

MEETINGS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/community/105)

Link to Agenda items

---

sig-windows/README.md

As discussed, based on Kubernetes.

Initial content for the Windows Working Group

---

README.md
group-aws/README.md
group-vmware/README.md

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Proposal for creating VMware SIG

---

PR-FLOW.md

Fix typo on PR-FLOW documentation.

Fix typo on PR-FLOW documentation.

---

WORKING-GROUPS.md

An initial swag at guidelines. Would close #170.

[WIP] Working Group Guidelines

---

README.md
ansible_community_meetings.ics

similar to #201, cc  @pilou- @dagwieers
- I edited an .ics file directly, is that safe?
Imported into Google Calendar and looks OK:

Fix broken MEETINGS.md links, meetings/ dir seems to be the new place

---

group-aws/bestpractices.md

Update AWS bestpractices.md

---

group-container/README.md

Hello, can I be part of Container WG?
@ryansb @j00bar

add me to container wg

---

group-aws/boto3.md
group-aws/review.md

Update boto module statuses and PR and issue statistics for AWS group

AWS status update

---

group-network/README.md

@grastogi23 and @ericsysmin added

added Avi Networks members

---

group-network/README.md

There was an erroneous space in my membership line

---

group-aws/README.md

Add badges to AWS README

---

group-aws/review.md

Fix the table markdown formatting
Add a note about the core/extras module repos migration

Fix table formatting and add numbers note

---

group-aws/integration.md

Document a policy for tests for AWS modules

Add an integration test policy for AWS WG

---

group-network/README.md

Adding myself for Cisco NSO per advice from @gundalow.

Adding myself

---

group-azure/README.md

@nitzmahone Hi Matt, could you please have a review? I will define the meeting later.

create community group for Azure

---

group-aws/boto3.md
group-aws/review.md

Add AWS stats info for November

Update AWS stats for November

---

group-network/roles_development_process.rst

Details on how we develop & release roles

Roles versions and dev process

---

group-network/roles_development_process.rst

- Added some more steps in _Adding & Enabling Zuul_ section

group-network: Added new entries in roles dev doc

---

group-network/README.md

Added group-network community README with github handle.

Adding Sumit's github alias in group-network

---

WORKING-GROUPS.md

Flesh out the docs a bit to ensure we have a consistent structure
See also https://github.com/ansible/community/pull/371

Improve "How to create working Group" docs

---

WORKING-GROUPS.md

Need to document how to setup a Working Group.

Process for creating Working Groups

---

ansible_community_meetings.ics
meetings/ical/lockdown.ics
meetings/lockdown.yaml

When I ran make it seemed to have updated other icals, i didnt include those changes but i can add them if that is preferred

lockdown meeting

---

group-aws/boto3.md

Started with a PR for using boto3 modules for dynamodb
Not much success on getting CI success, it always fails with cancelled.
Also, need help if to do more unit tests. I couldn't do much , I wasn't sure if we have any unit tests and if do , is there any particular mock interface we need to use.

PR for using boto3 in dynamodb module

---

meetings/README.md

Be explicit about which IRC channel
Thanks to @aknrdureegaesr for pointing this out

Avoid confusion regarding IRC channels

---

group-aws/boto3.md

- Update boto3.md
- It is out of order because the syntax to sort is missing
- Docs Pull Request
group-aws/boto3.md
```paste below
master
```

Update boto3.md - add sort

---

meetings/docs.yaml

We've agreed to meet earlier this summer, since many of our regulars are in EMEA.

reflects earlier meeting time

---

meetings/README.md

Signed-off-by: Sandra McCann <samccann@redhat.com>

update Docs meeting to 14:30 UTC

---

ansible_community_meetings.ics
meetings/README.md
meetings/ical/security.ics
meetings/security.yaml

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Update Ansible Security iCal file

---

group-security/README.md
group-security/bestpractices.md
group-security/integration.md
group-security/review.md

Building Security community page

---

meetings/README.md
meetings/read_minutes.py

Not entirely sure where to stick this.

Add link to meeting summarizer

---

ansible_community_meetings.ics
meetings/README.md
meetings/diversity.yaml
meetings/ical/diversity.ics

Description and ical file for new biweekly meeting

Add D&I working group meeting information

---

ansible_community_meetings.ics
meetings/README.md
meetings/core-team.yaml
meetings/ical/core-team.ics

One meeting a week, alternating between Tuesday and Thursday.

Update Ansible Core IRC meeting schedule

---

README.md

main not master

---

group-aws/utility-modules.md

Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

Fix a typo higer -> higher

---

decks/README.md
decks/ansible-plugins.html

Deck is designed for a meetup (20ish minutes talk, 10 discussion).

Add presentation deck of eqrx about ansible plugins

---

meetings/README.md
meetings/aws.yaml
meetings/ical/aws.ics

Create meeting ical for AWS Working Group -  not sure if this is enough, I'll need some guidance otherwise.

Create meeting ical for AWS Working Group

---

group-aws/utility-modules.md

Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

Fix a typo expecially -> especially

---

README.md
WORKING-GROUPS.md

Update README.md and WORKING-GROUP.md
Please suggest things to add, change or remove

Update README.md and WORKING-GROUP.md

---

ansible_community_meetings.ics

ansible_community_meetings.ics: remove testing and lockdown

ansible_community_meetings.ics: remove testing and lockdown

---

README.md
WORKING-GROUPS.md

Relates to https://forum.ansible.com/t/teams-community-building-blocks/182

Working Group info: add Forum

---

ansible_community_meetings.ics
meetings/community.yaml
meetings/ical/community.ics

Summer time ended last weekend in most of Europe and it ends this
weekend in the US.
Relates: 5877e906df731d67ef83c28ca2bbfd5627e0dfa1

switch community meeting 19:00 UTC
